---
name: "pre-release"

on:
  push:
    branches-ignore:
      - master

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.15.x'
      - name: Checkout Code
        uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}

      - name: Set GOPATH, PATH and ENV
        run: |
          echo "GOPATH=$(dirname $GITHUB_WORKSPACE)" >> $GITHUB_ENV
          echo "GO111MODULE=on" >> $GITHUB_ENV
          echo "GOPROXY=https://proxy.golang.org" >> $GITHUB_ENV
          echo "$(dirname $GITHUB_WORKSPACE)/bin" >> $GITHUB_PATH
          echo "BRANCHNAME=$(echo $GITHUB_REF | rev | cut -d / -f1 | rev)" >> $GITHUB_ENV
        shell: bash

      - name: build release
        run: |
          ls -la
          cd $GITHUB_WORKSPACE
          make build-all
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          title: "Development Build - Branch ${{ env.BRANCHNAME }}"
          files: |
            *.tgz




